name: daka

on:
  push:
  schedule:
    - cron: '0 17 * * *'

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1

    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: install
      run: 
        python -m pip install --upgrade pip 
        
    - name: install requests
      run: 
        pip install requests


    - name: install beautifulsoup4
      run: 
        pip install beautifulsoup4
      
    - name: run
      run: 
        python main.py
